### ISSUE TITLE
Create Zone

### ISSUE THREAD

**Issue by next-sentence** [adbutler/adbutler-php#1]
Is there any way to create zone using this API?

**Comment by baig** [comment]
Yes, see the [zone], [banner zones], [email zones], and [text zones] sections in the [API Documentation].

[zone]: http://www.adbutler.com/docs/api/?php#zones
[banner zones]: http://www.adbutler.com/docs/api/?php#banner-zones
[email zones]: http://www.adbutler.com/docs/api/?php#email-zones
[text zones]: http://www.adbutler.com/docs/api/?php#text-zones
[API Documentation]: http://www.adbutler.com/docs/api/?php
